openapi: 3.0.0
info:
  title: API de Reseñas
  description: API para gestionar reseñas de libros por parte de clientes.
  version: 1.0.0

servers:
  - url: http://107.20.212.250:8000
    description: Servidor de desarrollo

paths:
  /reviews:
    get:
      summary: Obtener todas las reseñas
      responses:
        '200':
          description: Un arreglo JSON de reseñas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
    post:
      summary: Crear una nueva reseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '201':
          description: Reseña creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Error en la solicitud

  /reviews/cliente/{id_cliente}:
    get:
      summary: Obtener reseñas por ID de cliente
      parameters:
        - in: path
          name: id_cliente
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reseñas del cliente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '404':
          description: No se encontraron reseñas para el cliente

  /reviews/libro/{id_libro}:
    get:
      summary: Obtener reseñas por ID de libro
      parameters:
        - in: path
          name: id_libro
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reseñas del libro
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '404':
          description: No se encontraron reseñas para el libro

  /reviews/{id}:
    put:
      summary: Actualizar una reseña por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '200':
          description: Reseña actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Reseña no encontrada
    delete:
      summary: Eliminar una reseña por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reseña eliminada exitosamente
        '404':
          description: Reseña no encontrada

components:
  schemas:
    Review:
      type: object
      properties:
        id:
          type: string
          description: ID de la reseña
        id_libro:
          type: string
          description: ID del libro
        id_cliente:
          type: string
          description: ID del cliente que escribió la reseña
        puntuacion:
          type: integer
          description: Puntuación otorgada al libro (1-5)
        resena:
          type: string
          description: Texto de la reseña
        fecha:
          type: string
          format: date
          description: Fecha en la que se escribió la reseña
      required:
        - id_libro
        - id_cliente
        - puntuacion
        - resena
